[build]
  command = "npm rebuild @tailwindcss/node && prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PLATFORM = "linux"
  NPM_CONFIG_ARCH = "x64"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200